# Put this file to your ~/.config/starship.toml

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''
commit_hash_length = 4
tag_symbol = 'ğŸ”– '
ignore_branches = ['master', 'main']

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

# Display account and aliased region
[gcloud]
symbol = 'ï¸ğŸ‡¬ï¸ '
[gcloud.region_aliases]
us-central1 = 'uc1'
asia-northeast1 = 'an1'
